name: Automated update

on:
  workflow_dispatch:
  schedule:
    - cron: "55 23 * * *"

permissions:
  contents: write
jobs:
  auto_update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ruby/setup-ruby@v1.213.0
        with:
          bundler-cache: true
      - name: Update benchmarks submodule
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Process benchmark data
        run: ./bin/process_benchmark_data
      - name: Commit changes
        run: |
          git config --global user.name 'RPR Auto-update'
          git config --global user.email 'ar2em1s@users.noreply.github.com'
          git commit --allow-empty -am "Auto-update $(date '+%Y-%m-%d')"
          git push
